# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: heroku_connect_development
  pool: 5
  username: postgres
  password: postgres
  schema_search_path: "salesforce,public"

test:
  adapter: postgresql
  encoding: unicode
  database: heroku_connect_test
  pool: 5
  username: postgres
  password: postgres
  schema_search_path: "salesforce,public"

production:
  adapter: postgresql
  encoding: unicode
  database: heroku_connect_prod
  pool: 5
  username: postgres
  password: postgres
  schema_search_path: "salesforce,public"

cucumber:
  adapter: postgresql
  encoding: unicode
  database: heroku_connect_test
  pool: 5
  username: postgres
  password: postgres
  schema_search_path: "salesforce,public"